### ISSUE TITLE
logbook very slow

### ISSUE THREAD

**Issue by KaiDol** [inofix/flussbad-modules#301] opened 2015-11-03 08:36 UTC
error loading .js file seems to prevent logbook from quick loading.

**Comment by chrberndt** [comment] 2015-11-03 12:03
We can reproduce the issue but we don't think the js is the cause. We see Exceptions in the log when the logbook is requested, which we will have to investigate.

**Comment by chrberndt** [comment] 2015-11-03 16:47
There is an issue with the project- / logbook article template which causes these exceptions. This will be fixed soon.

**Comment by chrberndt** [comment] 2015-11-03 19:45
We have removed and re-created the logbook layout anew. Assetpublisher and categories-navigation have been redeployed. No more exceptions in catalina.out. Uncached logbook requests are now served well below 2 seconds which is fine for dynamically created pages.

**Closed as completed by chrberndt** 2015-11-03 19:45 UTC
Labels: bug
